class AppStrings {
  static String _lang = 'en';
  static void setLanguage(String lang) => _lang = lang;
  static String get currentLang => _lang;
  static String get(String key) => _s[_lang]?[key] ?? _s['en']?[key] ?? key;

  static const Map<String, Map<String, String>> _s = {
    'en': {
      'app_name':'FactoryFlow','admin_title':'Admin Verification',
      'admin_subtitle':'Enter credentials to activate app',
      'admin_id':'Admin ID','admin_password':'Password',
      'activate':'Activate App','wrong_credentials':'Wrong ID or Password',
      'home':'Home','production':'Production','transport':'Transport',
      'inventory':'Inventory','billing':'Billing','purchase':'Purchase',
      'workers':'Workers','transporters':'Transporters','customers':'Customers',
      'suppliers':'Suppliers','quotations':'Quotations','reports':'Reports',
      'archives':'Excel Archives','settings':'Settings',
      'today':'Today','all_time_total':'All Time Total',
      'total_stock':'Total Stock','total_sales':'Total Sales',
      'total_purchase':'Total Purchase','transport_cost':'Transport Cost',
      'worker_cost':'Worker Cost','overview':'Overview',
      'date':'Date','save':'Save','cancel':'Cancel','edit':'Edit',
      'delete':'Delete','add':'Add','search':'Search','filter':'Filter',
      'export':'Export','notes':'Notes','photo':'Photo (Optional)',
      'name':'Name','phone':'Phone','address':'Address','total':'Total',
      'amount':'Amount','rate':'Rate','quantity':'Quantity','unit':'Unit',
      'size':'Size','no_data':'No data found','loading':'Loading...',
      'confirm_delete':'Confirm Delete',
      'delete_msg':'This will reverse all stock changes. Continue?',
      'yes':'YES','no':'NO',
      'add_production':'Add Production','edit_production':'Edit Production',
      'worker':'Worker','select_worker':'Select Worker','add_worker':'Add Worker',
      'product':'Product','total_amount':'Total Amount',
      'add_transport':'Add Transport','transporter':'Transporter',
      'vehicle':'Vehicle','vehicle_number':'Vehicle Number (Optional)',
      'delivery_location':'Delivery Location','client':'Client Name',
      'cement_bags':'Cement Bags','sand':'Sand (Optional)',
      'grit':'Grit (Optional)','rent':'Rent ₹',
      'add_purchase':'Add Purchase','supplier':'Supplier',
      'material':'Material','grade':'Grade / Spec','petrol_pump':'Petrol Pump',
      'create_invoice':'Create Invoice','invoice_number':'Invoice Number',
      'customer':'Customer','service':'Service','service_name':'Service Name',
      'default_service':'RCC Precast Compound Wall',
      'gst':'GST','affect_stock':'Affect Stock?',
      'subtotal':'Subtotal','gst_amount':'GST Amount',
      'generate_invoice':'Generate Invoice',
      'new_quote':'New Quotation','quote_number':'Quote Number',
      'convert_invoice':'Convert to Invoice',
      'status_draft':'Draft','status_sent':'Sent','status_approved':'Approved',
      'company_name':'Company Name','gst_number':'GST Number',
      'language':'Language','theme':'Theme',
      'dark_mode':'Dark Mode','light_mode':'Light Mode',
      'storage':'Auto Storage (saves Excel to phone)',
      'payment_terms':'Payment Terms','terms_conditions':'Terms & Conditions',
      'export_excel':'Export to Excel','new_cycle':'Start New Cycle',
      'active_cycle':'ACTIVE','download':'Download','view_file':'View',
      'cycle_started':'New cycle started!','from':'From','to':'To',
      'total_earnings':'Total Earnings','total_items':'Total Items',
      'total_trips':'Total Trips','total_rent':'Total Rent Earned',
      'total_business':'Total Business','total_invoices':'Total Invoices',
      'history':'History','all_sheets':'All Sheets',
      'panel':'Panel','column':'Column',
    },
    'gu': {
      'app_name':'FactoryFlow','admin_title':'એડમિન વેરિફિકેશન',
      'admin_subtitle':'એપ એક્ટિવેટ કરવા ક્રેડેન્શિયલ દાખલ કરો',
      'admin_id':'એડમિન ID','admin_password':'પાસવર્ડ',
      'activate':'એપ એક્ટિવેટ કરો','wrong_credentials':'ખોટો ID અથવા પાસવર્ડ',
      'home':'હોમ','production':'ઉત્પાદન','transport':'ટ્રાન્સ',
      'inventory':'ઇન્વેન્ટરી','billing':'બિલિંગ','purchase':'ખરીદી',
      'workers':'કામદારો','transporters':'ટ્રાન્સ','customers':'ગ્રાહકો',
      'suppliers':'સપ્લાયર','quotations':'ક્વૉટેશન','reports':'રિપૉર્ટ',
      'archives':'Excel આર્કાઇવ','settings':'સેટિંગ્સ',
      'today':'આજ','all_time_total':'કુલ સારાંશ',
      'total_stock':'કુલ સ્ટૉક','total_sales':'કુલ વેચાણ',
      'total_purchase':'કુલ ખરીદી','transport_cost':'ટ્રાન્સ ખર્ચ',
      'worker_cost':'કામદાર ખર્ચ','overview':'ઝલક',
      'date':'તારીખ','save':'સેવ','cancel':'રદ','edit':'સુધારો',
      'delete':'ડિલીટ','add':'ઉમેરો','search':'શોધો','filter':'ફિલ્ટર',
      'export':'નિકાસ','notes':'નોંધ','photo':'ફોટો (વૈ.)',
      'name':'નામ','phone':'ફોન','address':'સરનામું','total':'કુલ',
      'amount':'રકમ','rate':'ભાવ','quantity':'જથ્થો','unit':'એકમ',
      'size':'સાઇઝ','no_data':'કોઈ ડેટા નથી','loading':'લોડ થઈ રહ્યું...',
      'confirm_delete':'ડિલીટ કન્ફર્મ','delete_msg':'સ્ટૉક ફેરફાર પૂર્વવત્ થશે. ચાલુ?',
      'yes':'હા','no':'ના',
      'add_production':'ઉત્પાદન ઉમેરો','edit_production':'ઉત્પાદન સુધારો',
      'worker':'કામદાર','select_worker':'કામદાર પસંદ','add_worker':'કામદાર ઉમેરો',
      'product':'ઉત્પાદ','total_amount':'કુલ રકમ',
      'add_transport':'ટ્રાન્સ ઉમેરો','transporter':'ટ્રાન્સ',
      'vehicle':'વાહન','vehicle_number':'વાહન નં. (વૈ.)',
      'delivery_location':'ડિલિવરી સ્થળ','client':'ક્લાઇન્ટ',
      'cement_bags':'સિ. બૅગ','sand':'રેતી (વૈ.)','grit':'ગ્રિટ (વૈ.)','rent':'ભાડું ₹',
      'add_purchase':'ખરીદી ઉમેરો','supplier':'સપ્લાયર',
      'material':'સામગ્રી','grade':'ગ્રેડ','petrol_pump':'પેટ્રોલ પંપ',
      'create_invoice':'ઇન્વૉઇસ','invoice_number':'ઇ. નં.',
      'customer':'ગ્રાહક','service':'સેવા','service_name':'સેવા નામ',
      'default_service':'RCC Precast Compound Wall',
      'gst':'GST','affect_stock':'સ્ટૉક ઘટે?',
      'subtotal':'પેટા કુલ','gst_amount':'GST રકમ','generate_invoice':'ઇન્વૉઇસ બનાવો',
      'new_quote':'નવો ક્વૉટ','quote_number':'ક્વૉ. નં.',
      'convert_invoice':'ઇ. બનાવો','status_draft':'ડ્રાફ્ટ',
      'status_sent':'મોકલ્યો','status_approved':'મંજૂર',
      'company_name':'કંપની નામ','gst_number':'GST નં.',
      'language':'ભાષા','theme':'થીમ','dark_mode':'ડાર્ક','light_mode':'લાઇટ',
      'storage':'ઑટો Excel સ્ટોરેજ','payment_terms':'ચ. શરતો',
      'terms_conditions':'નિ. શરતો','export_excel':'Excel','new_cycle':'નવો ચક્ર',
      'active_cycle':'ચાલુ','download':'ડા.','view_file':'જુઓ',
      'cycle_started':'નવો ચક્ર શરૂ!','from':'થી','to':'સુધી',
      'total_earnings':'કુલ કમાણી','total_items':'કુલ વસ્તુ',
      'total_trips':'કુલ ટ્રિપ','total_rent':'કુલ ભાડું',
      'total_business':'કુલ વ્યવસાય','total_invoices':'કુલ ઇ.',
      'history':'ઇ.','all_sheets':'બધા','panel':'પૅ.','column':'ક.',
    },
    'hi': {
      'app_name':'FactoryFlow','admin_title':'एडमिन वेरिफिकेशन',
      'admin_subtitle':'ऐप एक्टिवेट करने के लिए क्रेडेंशियल दर्ज करें',
      'admin_id':'एडमिन ID','admin_password':'पासवर्ड',
      'activate':'ऐप एक्टिवेट करें','wrong_credentials':'गलत ID या पासवर्ड',
      'home':'होम','production':'उत्पादन','transport':'परिवहन',
      'inventory':'इन्वेंटरी','billing':'बिलिंग','purchase':'खरीद',
      'workers':'कार्यकर्ता','transporters':'ट्रांसपोर्टर','customers':'ग्राहक',
      'suppliers':'सप्लायर','quotations':'कोटेशन','reports':'रिपोर्ट',
      'archives':'Excel आर्काइव','settings':'सेटिंग्स',
      'today':'आज','all_time_total':'कुल सारांश',
      'total_stock':'कुल स्टॉक','total_sales':'कुल बिक्री',
      'total_purchase':'कुल खरीद','transport_cost':'परिवहन लागत',
      'worker_cost':'मजदूर लागत','overview':'अवलोकन',
      'date':'तारीख','save':'सहेजें','cancel':'रद्द','edit':'संपादित',
      'delete':'हटाएं','add':'जोड़ें','search':'खोजें','filter':'फ़िल्टर',
      'export':'निर्यात','notes':'नोट्स','photo':'फोटो (वैकल्पिक)',
      'name':'नाम','phone':'फोन','address':'पता','total':'कुल',
      'amount':'राशि','rate':'दर','quantity':'मात्रा','unit':'इकाई',
      'size':'आकार','no_data':'कोई डेटा नहीं','loading':'लोड हो रहा है...',
      'confirm_delete':'हटाने की पुष्टि',
      'delete_msg':'यह स्टॉक परिवर्तन वापस करेगा। जारी रखें?',
      'yes':'हाँ','no':'नहीं',
      'add_production':'उत्पादन जोड़ें','edit_production':'उत्पादन संपादित',
      'worker':'कार्यकर्ता','select_worker':'कार्यकर्ता चुनें',
      'add_worker':'कार्यकर्ता जोड़ें','product':'उत्पाद','total_amount':'कुल राशि',
      'add_transport':'परिवहन जोड़ें','transporter':'ट्रांसपोर्टर',
      'vehicle':'वाहन','vehicle_number':'वाहन नंबर (वैकल्पिक)',
      'delivery_location':'डिलीवरी स्थान','client':'ग्राहक नाम',
      'cement_bags':'सीमेंट बैग','sand':'रेत (वैकल्पिक)',
      'grit':'गिट्टी (वैकल्पिक)','rent':'किराया ₹',
      'add_purchase':'खरीद जोड़ें','supplier':'सप्लायर',
      'material':'सामग्री','grade':'ग्रेड','petrol_pump':'पेट्रोल पंप',
      'create_invoice':'इनवॉइस बनाएं','invoice_number':'इ. नं.',
      'customer':'ग्राहक','service':'सेवा','service_name':'सेवा नाम',
      'default_service':'RCC Precast Compound Wall',
      'gst':'GST','affect_stock':'स्टॉक घटाएं?',
      'subtotal':'उप-कुल','gst_amount':'GST राशि',
      'generate_invoice':'इनवॉइस बनाएं','new_quote':'नया कोटेशन',
      'quote_number':'कोट नं.','convert_invoice':'इनवॉइस बनाएं',
      'status_draft':'ड्राफ्ट','status_sent':'भेजा','status_approved':'स्वीकृत',
      'company_name':'कंपनी नाम','gst_number':'GST नं.',
      'language':'भाषा','theme':'थीम','dark_mode':'डार्क','light_mode':'लाइट',
      'storage':'ऑटो Excel स्टोरेज','payment_terms':'भुगतान शर्तें',
      'terms_conditions':'नियम व शर्तें','export_excel':'Excel निर्यात',
      'new_cycle':'नया चक्र','active_cycle':'सक्रिय',
      'download':'डाउनलोड','view_file':'देखें',
      'cycle_started':'नया चक्र शुरू!','from':'से','to':'तक',
      'total_earnings':'कुल कमाई','total_items':'कुल आइटम',
      'total_trips':'कुल ट्रिप','total_rent':'कुल किराया',
      'total_business':'कुल व्यापार','total_invoices':'कुल इ.',
      'history':'इतिहास','all_sheets':'सभी','panel':'पैनल','column':'कॉलम',
    },
  };
}
